# Code for data pre-processing
library(tidyr)
library(dplyr)
library(tictoc)

#################################################
# The preprocessing() function takes as input:
#     1. The file name of a Protein Quantitative csv report generated by Spectranaut 
#     2. A Boolean specifying whether or not to filter out results that are NaN

# The function then executes the following:
#   1. reads the file 
#   2. if applicable, filters NaN 
#   3. provides summary statistics and histogram of all values reported in the 
#     data set
#   4. selects columns that provide necessary information for analysis
#   5. re-formats the data to present individual proteins as columns and groups 
#     replicates under each protein
#   6. stores the data as a data.frame and prints a few columns to provide a 
#     visual example to the user. 

# Finally, the function returns the pre-processed data.
#################################################


preprocessing <- function(fileName, filterNaN = TRUE){
    # read in the protein quantitative csv file generated from Spectranaut
    rawData <- read.csv(fileName)
    
    if (filterNaN) {
    # filter out the proteins that have no recorded value
    naNFilteredData <- rawData %>% filter(!is.nan(PG.Quantity))
    }
    
    # select columns necessary for analysis 
    selectedData <- naNFilteredData %>% select(R.FileName, R.Replicate,  
                                               PG.Quantity, PG.ProteinNames)
    
    # print summary statistics for full raw data set
    cat("Summary of full data signals (raw)")
    print(summary(selectedData$PG.Quantity))
    cat("\n")
    
    # generate histogram of log2 -transformed full data set values 
    hist(log2(selectedData$PG.Quantity), main = "Histogram of Full Data Set", 
         xlab = "Log2(Data)", breaks = "Scott")
    
    # reformat data to present proteins as the columns
    # and to group replicates under each protein
    reformatedData <- selectedData %>% pivot_wider(id_cols = c(R.FileName, R.Replicate),
                              names_from = PG.ProteinNames, values_from = PG.Quantity)
    
    # store data in a data frame structure
    loadedData <- reformatedData %>% data.frame() 
    
    #Provide sample data for visual inspection
    cat("Example Structure of Pre-Processed Data")
    print(loadedData[,1:5])
    
    # return pre-processed data
    return(loadedData)
}


dat <- preprocessing("ProteinQuantReport.csv")




