---
title: "FAQ"
output: rmarkdown::html_vignette
bibliography:
  - ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{faq}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Installation


**1\. `WARNING: Rtools is required to build R packages but is not currently installed.`**


For Windows, the [RTools](https://cran.r-project.org/bin/windows/Rtools/)
is required to build this package.


**2\. `sh: /opt/gfortran/bin/gfortran: No such file or directory`**


The [GFortran](https://fortran-lang.org/learn/os_setup/install_gfortran/)
compiler is required to build this package.


**3\. `dependency 'impute' is not available`**


There are dependent packages—[impute](https://bioconductor.org/packages/impute/),
[limma](https://bioconductor.org/packages/limma/), and
[pcaMethods](https://bioconductor.org/packages/pcaMethods/)—that are available
via Bioconductor rather than CRAN. If you get an error message about these
packages, simply install them using:


```
install.packages("BiocManager")
BiocManager::install("impute")
BiocManager::install("limma")
BiocManager::install("pcaMethods")
```


## Original data


**1\. Can I use msDiaLogue to analyze data exported from Scaffold?**


Please refer to [Instructions for Exporting Data from Scaffold for Use in msDiaLogue Analysis](scaffold.html).


## Visualization


**1\. Can I customize the volcano plot generated by msDiaLogue?**


Please refer to [Customizing msDiaLogue Visualizations](cust_vis.html).

