# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "R.Condition", # <dataMissing>
  "R.Replicate", # <dataMissing>
  "variable", # <dataMissing>
  "value", # <dataMissing>
  "PG.Quantity", # <preProcessFiltering>
  "PG.NrOfStrippedSequencesIdentified", # <preProcessFiltering>
  "PG.ProteinNames", # <preProcessFiltering>
  "PG.ProteinAccessions", # <preProcessFiltering>
  "value", # <preprocessing>
  "PG.Genes", # <preprocessing>
  "PG.ProteinAccessions", # <preprocessing>
  "PG.ProteinDescriptions", # <preprocessing>
  "PG.ProteinNames", # <preprocessing>
  "R.Condition", # <preprocessing>
  "R.Replicate", # <preprocessing>
  "PG.Quantity", # <preprocessing>
  ".", # <preprocessing_scaffold>
  "AccessionNumber", # <preprocessing_scaffold>
  "ConditionReplicate", # <preprocessing_scaffold>
  "R.Condition", # <preprocessing_scaffold>
  "R.Replicate", # <preprocessing_scaffold>
  "Quantity", # <preprocessing_scaffold>
  "value", # <preprocessing_scaffold>
  "Mean", # <meanVarPlot>
  "Variance", # <meanVarPlot>
  "R.Condition", # <visualize.heatmap>
  "R.Replicate", # <visualize.heatmap>
  "R.ConRep", # <visualize.heatmap>
  "name", # <visualize.heatmap>
  "value", # <visualize.heatmap>
  "Regulation", # <visualize.ma>
  "Variable", # <visualize.ma>
  "A", # <visualize.ma>
  "M", # <visualize.ma>
  "label", # <visualize.ma>
  "Variable", # <visualize.test>
  "name", # <visualize.test>
  "value", # <visualize.test>
  "Comparison", # <visualize.test>
  "binwidth", # <visualize.test>
  "Significant", # <visualize.volcano>
  "Variable", # <visualize.volcano>
  "difference", # <visualize.volcano>
  "p.value", # <visualize.volcano>
  "label", # <visualize.volcano>
  NULL
))
