##
## msDiaLogue: Analysis + Visuals for Data Indep. Aquisition Mass Spectrometry Data
## Copyright (C) 2024  Shiying Xiao, Timothy Moore and Charles Watt
## Shiying Xiao <shiying.xiao@uconn.edu>
##
## This file is part of the R package msDiaLogue.
##
## The R package msDiaLogue is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package wdnet is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "R.Condition", # <analyze>
  "R.Replicate", # <analyze>
  "PG.Quantity", # <preProcessFiltering>
  "PG.NrOfStrippedSequencesIdentified", # <preProcessFiltering>
  "PG.ProteinNames", # <preProcessFiltering>
  "PG.ProteinAccessions", # <preProcessFiltering>
  "value", # <preprocessing>
  "R.Condition", # <preprocessing>
  "R.FileName", # <preprocessing>
  "R.Replicate", # <preprocessing>
  "PG.Quantity", # <preprocessing>
  "PG.ProteinNames", # <preprocessing>
  "PG.ProteinAccessions", # <preprocessing>
  "R.FileName", # <sortcondition>
  "R.Replicate", # <sortcondition>
  "R.Condition", # <sortcondition>
  "R.FileName", # <summarize>
  "R.Replicate", # <summarize>
  ".", # <summarize>
  "Mean", # <meanVarPlot>
  "Variance", # <meanVarPlot>
  "R.Condition", # <visualize>
  "R.FileName", # <visualize>
  "R.Replicate", # <visualize>
  "R.ConRep", # <visualize>
  "value", # <visualize>
  "Significant", # <visualize>
  "A", # <visualize>
  "M", # <visualize>
  "delabel", # <visualize>
  "RowName", # <visualize>
  "binwidth", # <visualize>
  "Difference", # <visualize>
  "P.value", # <visualize>
  NULL
))
