##
## msDiaLogue: Analysis + Visuals for Data Indep. Aquisition Mass Spectrometry Data
## Copyright (C) 2025  Shiying Xiao, Timothy Moore and Charles Watt
## Shiying Xiao <shiying.xiao@uconn.edu>
##
## This file is part of the R package msDiaLogue.
##
## The R package msDiaLogue is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package msDiaLogue is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

#' Compiling data on a single protein from each step in the process
#' 
#' @description
#' Summarize the steps performed on the data for one protein.
#' 
#' @param listName A character vector identifying the proteins of interest.
#' 
#' @param regexName A character vector specifying the proteins for regular expression
#' pattern matching.
#' 
#' @param by A character string specifying the information to which the \code{listName}
#' and/or \code{regexName} are applied, with allowable options:
#' \itemize{
#' \item For Spectronaut: "PG.Genes", "PG.ProteinAccessions", "PG.ProteinDescriptions",
#' and "PG.ProteinNames".
#' \item For Scaffold: "ProteinDescriptions", "AccessionNumber", and "AlternateID".
#' }
#' 
#' @param dataSetList A list of data frames, the order dictates the order of presentation.
#' 
#' @param proteinInformation The name of the .csv file containing protein information data
#' (including the path to the file, if needed). The file should include the following
#' columns:
#' \itemize{
#' \item For Spectronaut: "PG.Genes", "PG.ProteinAccessions", "PG.ProteinDescriptions",
#' and "PG.ProteinNames".
#' \item For Scaffold: "ProteinDescriptions", "AccessionNumber", and "AlternateID".
#' }
#' This file is automatically generated by the function
#' \code{\link[msDiaLogue]{preprocessing}} or
#' \code{\link[msDiaLogue]{preprocessing_scaffold}}.
#' 
#' @return
#' A 2d dataframe, with the protein data at each step present in the \code{dataSetList}.
#' 
#' @export

pullProteinPath <- function(listName = NULL, regexName = NULL, dataSetList,
                            by = "PG.ProteinNames",
                            proteinInformation = "preprocess_protein_information.csv") {
  
  proteinInformation <- read.csv(proteinInformation)
  
  allName <- proteinInformation[[by]]
  
  ## only list filter if listName is present
  if (length(listName) != 0) {
    listIndex <- which(allName %in% listName)
  } else {
    listIndex <- NULL
  }
  
  ## only regex filter if regexName is present
  if (length(regexName) != 0) {
    regexIndex <- grep(paste(regexName, collapse = "|"), allName, value = FALSE)
  } else {
    regexIndex <- NULL
  }
  
  ## combine protein names from list and regex filters
  unionIndex <- union(listIndex, regexIndex)
  
  keyid <- ifelse(startsWith(by, "PG."), "PG.ProteinNames", "AccessionNumber")
  unionName <- proteinInformation[unionIndex, keyid]
  
  proteinPath <- do.call(rbind, lapply(unionName, function(name) {
    cbind(dataSetList[[1]][c("R.Condition", "R.Replicate")],
          name,
          sapply(dataSetList, function(data) data[[name]] %||% NA))
  }))
  
  colnames(proteinPath)[colnames(proteinPath) == "name"] <- keyid
  
  result <- merge(proteinInformation[unionIndex,], proteinPath,
                  by = keyid, sort = TRUE)
  
  return(result)
}

